apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-karavi-cloud
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
      - karavi.cloud
    secretName: karavi-cloud-tls
  rules:
  - host: karavi.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kf-api-svc
            port:
              number: 8080
